### ISSUE TITLE
Register is assinged in multiple always blocks

### ISSUE THREAD

**Issue by garikyes** [NNgen/nngen#43] opened 2022-02-24 11:19 UTC
I have followed the steps described in README to run the hello example.
When trying to synthesize the generated Verilog design with my synthesis tool it interrupts with an error message, complaining that there are registers which are being driven in multiple always blocks, e.g. the following register from hello.v is such an example:  _acc_0_stream_ivalid.

Is there a way/option to avoid multi-driven cases, as in general assignments in multiple always blocks (by the way with the same list of events) is not synthesisable?

**Comment by shtaxxx** [comment] 2022-04-12 10:37
Thank you for pointing out that critical problem. That was caused by the update of Veriloggen. It was resolved in 7ef5b4892a922c8945231d6a655711d5a30a8326 with https://github.com/PyHDI/veriloggen/releases/tag/2.1.0 .

**Closed as completed by shtaxxx** 2022-04-12 10:37 UTC
